# Site settings
title: Guichê Virtual
# email: fill with email
description: Conteúdo do Guichê Virtual
logo: static/gvlogo.png
mdl_colors: light_blue-orange
copyright: Guichê Virtual Serviços de Internet
search: true 

# jekyll setup
plugins:
  - jekyll-remote-theme
remote_theme: chromatical/jekyll-materialdocs
exclude:
  - Gemfile
  - Gemfile.lock
