# Site settings
title: Guichê Virtual
email: contato@guichevirtual.com.br
description: Conteúdo do Guichê Virtual
logo: static/gvlogo.png
mdl_colors: light_blue-orange
copyright: Guichê Virtual Serviços de Internet
search: false 
menu_style: dropdown

# jekyll setup
plugins:
  - jekyll-remote-theme
remote_theme: chromatical/jekyll-materialdocs
exclude:
  - Gemfile
  - Gemfile.lock
